version: '3.8'
name: higherlower
services:
  higherlower:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      higherlower-db:
        condition: service_healthy
    environment:
      - DB_URL
      - DB_USERNAME=$DB_MIGRATION_USERNAME
      - DB_PASSWORD=$DB_MIGRATION_PASSWORD

  higherlower-db:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=$DB_MIGRATION_PASSWORD
      - POSTGRES_USER=$DB_MIGRATION_USERNAME
    volumes:
      - ./create-test-db.sql:/docker-entrypoint-initdb.d/create-test-db.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: